name: Finalize Release
on:
  pull_request:
    types:
      - closed
    branches:
      - "rc/**"
  workflow_dispatch:
    inputs:
      ref:
        description: |
          The branch for which the finalize the release.
        required: true

jobs:
  finalize-release:
    if: (github.event_name == 'pull_request' && github.event.pull_request.merged == true) || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Determine ref
        env:
          REF_FROM_INPUT: ${{ inputs.ref }}
          REF_FROM_PR: ${{ github.event.pull_request.merge_commit_sha  }}
          BASE_REF_FROM_PR: ${{ github.event.pull_request.base.ref }}
        run: |
          if [[ $GITHUB_EVENT_NAME == "workflow_dispatch" ]]; then
            echo "REF=$REF_FROM_INPUT" >> "$GITHUB_ENV"
            echo "BASE_REF=$REF_FROM_INPUT" >> "$GITHUB_ENV"
          else
            echo "REF=$REF_FROM_PR" >> "$GITHUB_ENV"
            echo "BASE_REF=$BASE_REF_FROM_PR" >> "$GITHUB_ENV"
          fi

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.REF }}

      - name: Configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Create release tag
        run: |
          version=${BASE_REF#rc/}
          echo "Creating release tag v$version"

          git tag -a v$version -m "Release v$version"
          git push -f origin v$version

      - name: Finalize release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          version=${BASE_REF#rc/}
          echo "Finalizing release v$version"

          gh release edit "v$version" --tag v$version