name: Finalize Release

on:
  workflow_dispatch:
    inputs:
      head-sha:
        description: |
          The head SHA of the release PR to use for finalizing the release.
        required: true
  workflow_call:
    inputs:
      head-sha:
        type: string
        description: |
          The head SHA of the release PR to use for finalizing the release.
        required: true

env:
  HEAD_SHA: ${{ inputs.head-sha }}

jobs:
  update-release:
    name: "Update release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.head-sha }}

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r scripts/release/requirements.txt

      - name: Update release assets
        env:
          GITHUB_TOKEN: ${{ github.token }}
          RELEASE_ENGINEERING_TOKEN: ${{ secrets.RELEASE_ENGINEERING_TOKEN }}
        run: |
          python scripts/release/update-release-assets.py \
            --head-sha $HEAD_SHA \
            --layout scripts/release/release-layout.yml \
            --repo "$GITHUB_REPOSITORY" \
            --github-token "$GITHUB_REPOSITORY:$GITHUB_TOKEN" "github/codeql-coding-standards-release-engineering:$RELEASE_ENGINEERING_TOKEN" \
            --skip-checks

      - name: Update release notes
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          python scripts/release/update-release-notes.py \
            --head-sha $HEAD_SHA \
            --repo "$GITHUB_REPOSITORY" \
            --github-token "$GITHUB_TOKEN"
