name: "Prepare CodeQL Coding Standards release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: |
          The version to release (MUST follow semantic versioning).
        required: true
      ref:
        description: |
          The git commit, branch, or tag to release from.
        required: true
  # The following push event trigger is only used for testing purposes. Should be removed before merging!
  push:
    branches:
      - rvermeulen/release-process-improvements

permissions:
  contents: write
  pull-requests: write
  actions: write
  checks: write

env:
  RELEASE_VERSION: ${{ inputs.version }}

jobs:
  prepare-release:
    outputs:
      pull-request-head-sha: ${{ steps.create-release-pull-request.outputs.pull-request-head-sha }}
    name: "Prepare release"
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install release script dependencies
        run: pip install -r scripts/release/requirements.txt

      - name: Validate version
        run: |
          python scripts/release/validate-version.py "$RELEASE_VERSION"
      
      - name: Create release branch
        run: |
          git switch -c rc/$RELEASE_VERSION
          git push --set-upstream origin rc/$RELEASE_VERSION

      - name: Create feature branch for PR
        run: |
          git switch -c feature/update-user-manual-for-$RELEASE_VERSION
          git push --set-upstream origin feature/update-user-manual-for-$RELEASE_VERSION

      - name: Update user manual version
        run: |
          find docs -name 'user_manual.md' | xargs sed -i "s/code-scanning-cpp-query-pack-.*\.zip\`/code-scanning-cpp-query-pack-$RELEASE_VERSION.zip\`/"
          find docs -name 'user_manual.md' | xargs sed -i "s/supported_rules_list_.*\.csv\`/supported_rules_list_$RELEASE_VERSION.csv\`/"
          find docs -name 'user_manual.md' | xargs sed -i "s/supported_rules_list_.*\.md\`/supported_rules_list_$RELEASE_VERSION.md\`/"
          find docs -name 'user_manual.md' | xargs sed -i "s/user_manual_.*\.md\`/user_manual_$RELEASE_VERSION.md\`/"
          find docs -name 'user_manual.md' | xargs sed -i "s/This user manual documents release \`.*\` of/This user manual documents release \`$RELEASE_VERSION\` of/"

      - name: Create release PR
        id: create-release-pull-request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Release ${{ inputs.version }}."
          body: "This PR releases codeql-coding-standards version ${{ inputs.version }}."
          commit-message: "Update user manual for release ${{ inputs.version }}."
          delete-branch: true
          branch: "rc/${{ inputs.version }}"
  
  # Invoke release validation because our PRs created with a GitHub token do not trigger a `pull_request` event.
  validate-release:
    name: "Validate coding standards release"
    needs: prepare-release
    uses: ./.github/workflows/validate-release.yml
    with:
      ref: ${{ needs.prepare-release.outputs.pull-request-head-sha }}
    secrets:
      release-engineering-token: ${{ secrets.RELEASE_ENGINEERING_TOKEN }}